# Generated by Django 5.1.2 on 2024-10-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimModel',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_status', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=100)),
                ('date_of_service', models.DateField()),
                ('treatment_given', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_test', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_address', models.TextField()),
                ('hospital_city', models.CharField(max_length=100)),
                ('hospital_state', models.CharField(max_length=100)),
                ('hospital_pincode', models.CharField(max_length=10)),
                ('last_timestamp', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('isFinalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_address', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('type_of_plan', models.CharField(max_length=100)),
                ('claim_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='claim_app.claimmodel')),
            ],
        ),
        migrations.AddField(
            model_name='claimmodel',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='claim_app.patientmodel'),
        ),
    ]
